#ifndef MLK_CONFIG_H
#define MLK_CONFIG_H

#define MLK_CONFIG_PARAMETER_SET 512
#define MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#define MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#define MLK_CONFIG_NO_RANDOMIZED_API
#define MLK_CONFIG_NAMESPACE_PREFIX mlkem

#define MLK_CONFIG_ARITH_BACKEND_FILE "native/api.h"
#define MLK_CONFIG_FIPS202_BACKEND_FILE "fips202/native/api.h"

#endif
